When merging objects, even keys for invalid values should be remembered
necolas/styleq pull request #7
Opened 2022-12-13 04:48 UTC by nmn

The primary reason for this change is to support `null` values within compiled style objects.

In addition to that, *any* invalid value should also override previous values for that key. AFAIK, this is what React Native does. (Hard to say for sure since some invalid values will often throw an error).

2022-12-13 06:16 UTC, necolas requested changes
Needs unit tests for `null` case on compiled objects.

I will not accept the change where invalid values override valid values. Don't think that behavior makes sense. React Native apps will often crash on invalid values anyway. That's something on the roadmap to fix.

2022-12-14 07:29 UTC, nmn commented
> React Native apps will often crash on invalid values anyway. That's something on the roadmap to fix.

So the intention is to change RN to not throw on invalid values and ignore them instead? (like StyleQ does right now?)

---

Will update with more tests shortly.

2022-12-14 20:39 UTC, necolas commented
Yeah. Not throwing on invalid values is something Expo have been asking for

2022-12-15 18:45 UTC, closed without merging

2022-12-15 19:02 UTC, nmn commented
> Yeah. Not throwing on invalid values is something Expo have been asking for

We would need to ensure that invalid values don’t behave like “null” then.